# Generated by Django 4.2.30 on 2026-04-21 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo')),
                ('autor', models.CharField(max_length=100, verbose_name='Autor')),
                ('isbn', models.CharField(max_length=20, unique=True, verbose_name='ISBN')),
                ('exemplares_total', models.PositiveIntegerField(default=1, verbose_name='Total')),
                ('exemplares_disponiveis', models.PositiveIntegerField(default=1, verbose_name='Disponiveis')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('email', models.CharField(max_length=50, verbose_name='eMail')),
                ('celular', models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular')),
                ('funcao', models.CharField(choices=[('Leitor', 'Leitor'), ('Bibliotecario', 'Bibliotecario')], max_length=30, verbose_name='Funcao')),
                ('nascimento', models.DateField(blank=True, null=True, verbose_name='Nascimento')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_saida', models.DateField(auto_now_add=True, verbose_name='Saida')),
                ('data_devolucao_prevista', models.DateField(blank=True, null=True, verbose_name='Devolucao prevista')),
                ('data_devolucao_real', models.DateField(blank=True, null=True, verbose_name='Devolucao real')),
                ('leitor', models.ForeignKey(limit_choices_to={'funcao': 'Leitor'}, on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to='core.pessoa', verbose_name='Leitor')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to='core.livro', verbose_name='Livro')),
            ],
            options={
                'verbose_name': 'Emprestimo',
                'verbose_name_plural': 'Emprestimos',
                'ordering': ['-data_saida'],
            },
        ),
    ]
