# Generated by Django 4.2.30 on 2026-04-21 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livro',
            options={'ordering': ['titulo'], 'verbose_name': 'Obra', 'verbose_name_plural': 'Obras'},
        ),
        migrations.AddField(
            model_name='livro',
            name='ano',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ano'),
        ),
        migrations.AddField(
            model_name='livro',
            name='tipo_obra',
            field=models.CharField(choices=[('BIBLIOGRAFIA', 'Bibliografia'), ('TESE_DISSERTACAO', 'Tese/Dissertacao'), ('MONOGRAFIA', 'Monografia')], default='BIBLIOGRAFIA', max_length=20, verbose_name='Tipo de Obra'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to='core.livro', verbose_name='Obra'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='isbn',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='ISBN'),
        ),
    ]
