# Generated by Django 4.2.30 on 2026-04-21 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_livro_options_livro_ano_livro_tipo_obra_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivroEmbedding',
            fields=[
                ('livro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='embedding', serialize=False, to='core.livro', verbose_name='Obra')),
                ('vetor', models.BinaryField(verbose_name='Vetor (float32)')),
                ('texto_fonte', models.TextField(verbose_name='Texto usado no embedding')),
                ('modelo_versao', models.CharField(max_length=128, verbose_name='Modelo')),
                ('dimensao', models.PositiveIntegerField(verbose_name='Dimensao do vetor')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Embedding de Obra',
                'verbose_name_plural': 'Embeddings',
            },
        ),
    ]
